src/models/data/views.py
from flask import Blueprint, request, session, redirect, url_for, render_template
import os
import datetime
import pandas as pd
from src.common.flask_redirect import redirect_url
from src.models.users.decorators import requires_login
from src.models.users.user import User
from src.models.data.data_item import DataItem
from src.common.utils import Utils

data_blueprint = Blueprint('data', __name__)

uploaddir = os.path.join(os.path.dirname(os.path.abspath(__file__)), 
            os.path.normpath('../../../../uploaded'))

logger = Utils.get_logger(__name__)

@data_blueprint.route('/upload', methods=['POST'])
@requires_login
def handle_upload():

    ### Get file descriptions from form ###
    description = "NA" #request.form.get('dataUploadTextArea')


    ### Get user id ###
    userid = User.find_by_email(session["email"])._id

    ### Create data folder ###
    datadir = os.path.join(uploaddir,os.path.normpath("{}/".format(userid)))

    if not os.path.exists(datadir):
        os.mkdir(datadir)

    ### upload data ###
    h5_output_file = os.path.join(datadir,os.path.normpath("userdata.h5"))

    ### Store compress data has hd5
    with pd.HDFStore(h5_output_file, mode='a', complevel=9) as store:

        for key, f in request.files.items():
            if key.startswith('file'):
                
                ### data to server ###
                file = os.path.join(datadir, f.filename)
                f.save(file)

                ### Store csvfile in h5 format ###
                df = DataItem.import_csv(file)
                dataname = DataItem.get_dataset_name(file)
                columnsstring = ','.join(list(df.columns))
                filesize = os.path.getsize(file)

                ctr,dataname0 = 0,dataname
                while '/'+dataname in store.keys():
                    logger.warning("Dataset exists! Changing name in DB.")
                    dataname=dataname0+"_"+str(ctr)
                    ctr+=1

                store.put(dataname, df)                

                ### Create data object ###
                dataItem = DataItem(dataname, h5_output_file, userid, columnsstring, filesize, description=description).save_to_db()

                ### Delete csv file ###
                try:
                    os.remove(file)
                except:
                    logger.warning("Couldn't delete file: {}".format(file))

    return '', 204


@data_blueprint.route('/form', methods=['POST'])
def handle_form():
    description = request.form.get('dataUploadTextArea')
    return 'file uploaded and form submit<br>title: %s<br> description: %s' % ("title", description)


@data_blueprint.route('/explorer')
@requires_login
def explorer():
    return render_template("data/databrowser.html", dataItems=DataItem.getDataItems())
    

@data_blueprint.route('/remove')
@requires_login
def remove():

    
    item = DataItem.find_by_id(request.args.get('dataid'))
    
    if not item is None: 
        item.h5filepath
        item.dataname

        with pd.HDFStore(item.h5filepath) as store:
            store.remove(item.dataname)

        item.remove_from_DB()
        del item;
        return "DataItem deleted successfully!"


    return "Couldn't delete DataItem"

src/models/flowchart/views.py
from flask import Blueprint, request, session, redirect, url_for, render_template, jsonify
import json
from src.models.users.decorators import requires_login

fc_blueprint = Blueprint('flowchart', __name__)

@fc_blueprint.route('/')
@requires_login
def flowchart():
    return render_template('flowchart/flowchartNew.html', processes=["opt_mises.py","opt_forcedResponse.py"])


@fc_blueprint.route('/operatorData', methods=['POST'])
@requires_login
def operatorData():
    result = []
    data = request.get_json()
    print(data.keys())
    print(data['operators'].keys())
    print(data['operatorTypes'].keys())
    with open('graph.json', 'w') as json_file:
        json.dump(data, json_file, sort_keys=True, indent=4)

    return 'Export Successfull!'

@fc_blueprint.route('/sendJson', methods=['POST'])
@requires_login
def sendJson():

    ang = request.args.get('fucker', 0, type=str)

    with open('graph.json') as json_file:
        data = json.load(json_file)

    return jsonify({"output" : data})

src/models/users/views.py
from flask import Blueprint, request, session, redirect, url_for, render_template, flash
from src.models.users.user import User
from src.models.users.errors import UserNotExistsError
import src.models.users.errors as UserErrors
from src.models.users.decorators import requires_login
from src.common.flask_redirect import redirect_url

user_blueprint = Blueprint('users', __name__)

@user_blueprint.route('/login', methods=["GET","POST"])
def login_user():
    if request.method == "POST":
        # Check if login is valid

        email = request.form["userForm-email"]
        password = request.form["userForm-pass"]

        try:
            if User.is_login_valid(email, password):
                user = User.find_by_email(email)
                session["email"] = user.email
                session["username"] = user.username
                return redirect(redirect_url()) 

        except UserErrors.UserError as e:
            flash(e.message, 'login')

    return redirect(redirect_url()) 


@user_blueprint.route('/logout')
def logout_user():
    session["email"] = None
    session["username"] = None
    return redirect(url_for("home"))


@user_blueprint.route('/register', methods=["GET","POST"])
def register_user():
    if request.method == "POST":
        # Check if login is valid
        email = request.form["userRegisterForm-email"]
        password = request.form["userRegisterForm-pass"]
        username = request.form["userRegisterForm-name"]
        try:
            if User.register_user(email, password, username):
                session["email"] = email
                session["username"] = username
                return redirect(redirect_url())
        except UserErrors.UserError as e:
            flash(e.message, 'register')

    return redirect(redirect_url())     


# @user_blueprint.route('/alerts')
# @requires_login
# def user_alerts():
#     return redirect(url_for("stores.index"))



# @user_blueprint.route('/check_alerts/<string:user_id>')
# def check_user_alerts(user_id):
#     pass

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Advanced WebDesign</title>

    {% include 'html_dependencies.html' %}

</head>
<body>

<!-- Login form -->
<div class="modal fade" id="basemodalLoginForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content bg-light">
      <div class="modal-header">
        <h4 class="modal-title w-100 font-weight-bold">Login</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <!-- Body starts -->
      <div class="modal-body mx-3">

        <!-- Form -->
        <form action="{{ url_for('users.login_user')}}" method="post" id="userLoginForm">

          <div class="md-form mb-5">
            <i class="fas fa-envelope prefix grey-text"></i>
            <label data-error="wrong" data-success="right" for="userForm-email">Your email</label>
            <input type="email" name="userForm-email" id="userForm-email" class="form-control validate" placeholder="Enter email">
          </div>

          <div class="md-form mb-4">
            <i class="fas fa-lock prefix grey-text"></i>

            <label data-error="wrong" data-success="right" for="userForm-pass">Your password</label>
            <input type="password" name="userForm-pass" id="userForm-pass" class="form-control validate" placeholder="Password">
            
            {% with messages = get_flashed_messages(category_filter=["login"]) %}
               {% if messages %}
                  {% for message in messages %}
                     <small id="usererrorflash" class="form-text text-danger"> {{ message }} </small>
                  {% endfor %}
               {% endif %}
            {% endwith %}

          </div>
          <button type="submit" class="btn btn-secondary" id="loginsubmitbutton">Login</button> 

        </form>

      </div>
      <!-- Body Ends -->
      <div class="modal-footer d-flex justify-content-center">
        <!-- <button type="submit" class="btn btn-default" id="loginsubmitbutton">Login</button> -->
      </div>
      
    </div>
  </div>
</div>


<!-- Register form -->
<div class="modal fade" id="basemodalRegisterForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content bg-light">
      <div class="modal-header">
        <h4 class="modal-title w-100 font-weight-bold">Register</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <!-- Body starts -->
      <div class="modal-body mx-3">

        <!-- Form -->
        <form action="{{ url_for('users.register_user')}}" method="post" id="userRegisterForm">

          <div class="md-form mb-5">
            <i class="fas fa-envelope prefix grey-text"></i>
            <label data-error="wrong" data-success="right" for="userRegisterForm-name">Your Name</label>
            <input type="text" name="userRegisterForm-name" id="userRegisterForm-name" class="form-control validate" placeholder="Enter name">
          </div>

          <div class="md-form mb-5">
            <i class="fas fa-envelope prefix grey-text"></i>
            <label data-error="wrong" data-success="right" for="userRegisterForm-email">Your email</label>
            <input type="email" name="userRegisterForm-email" id="userRegisterForm-email" class="form-control validate" placeholder="Enter email">
          </div>

          <div class="md-form mb-4">
            <i class="fas fa-lock prefix grey-text"></i>
            <label data-error="wrong" data-success="right" for="userRegisterForm-pass">Your password</label>
            <input type="password" name="userRegisterForm-pass" id="userRegisterForm-pass" class="form-control validate" placeholder="Password">

            {% with messages = get_flashed_messages(category_filter=["register"]) %}
               {% if messages %}
                  {% for message in messages %}
                     <small id="usererrorflashregister" class="form-text text-danger"> {{ message }} </small>
                  {% endfor %}
               {% endif %}
            {% endwith %}

          </div>
          <button type="submit" class="btn btn-secondary" id="registersubmitbutton">Register</button> 

        </form>

      </div>
      <!-- Body Ends -->
      <div class="modal-footer d-flex justify-content-center">
        <!-- <button type="submit" class="btn btn-default" id="loginsubmitbutton">Login</button> -->
      </div>
      
    </div>
  </div>
</div>


<!-- Upload data form -->

{{ dropzone.load_css() }}
{{ dropzone.style('border: 2px dashed #0087F7; margin: 24px auto 24px auto; min-height: 400px; max-width: 575.98px') }}

<div class="modal fade" id="dataUploadModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true" data-backdrop="static">
  <div class="modal-dialog" role="document">
    <div class="modal-content bg-light">
      <div class="modal-header">
        <h4 class="modal-title w-100 font-weight-bold">Upload Data</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" id="modalclosebutton">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <!-- Body starts -->
      <div class="modal-body mx-3">

        <!-- Form -->
        <form action="{{ url_for('data.handle_form') }}" method="post" id="dataUploadForm">

          <div class="form-group">
            <label for="dataUploadTextArea">Description</label>
            <!-- <input type="text" class="form-control" id="datadescription" aria-describedby="datadescriptionHelp" placeholder="Enter name" name="dataUploadTextArea"/> -->
            <textarea name="dataUploadTextArea" class="form-control" id="dataUploadTextArea" rows="3" form="dataUploadForm"></textarea>
            <small id="datadescriptionHelp" class="form-text text-muted">Give a characteristic description for the data set.</small>
          </div>

          <div class="form-group">
            {{ dropzone.create() }}
          </div>
          
          <img id="loadinggif" src="{{ url_for('static', filename='img/gears.gif') }}" class="loading-gif">
          <input type="submit" id="submit" value="Upload" class="btn btn-secondary">
          <!-- <button type="submit" class="btn btn-secondary" id="submit">Upload</button>  -->
        </form>

      </div>
      <!-- Body Ends -->
      <div class="modal-footer d-flex justify-content-center">
        <!-- <button type="submit" class="btn btn-default" id="loginsubmitbutton">Login</button> -->
      </div>
      
    </div>
  </div>
</div>


<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <!-- <a class="navbar-brand" href="#">Navbar</a> -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        {% if session["email"] %}
          <a role="button" tabindex="0" class="nav-link" id="toggledataupload">Data Upload</a>
        {% else %}
          <a role="button" tabindex="0" class="nav-link disabled" id="toggledataupload">Data Upload</a>
        {% endif %}
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Analysis
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{{ url_for('data.explorer')}}">Data</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Feature Selection</a>
          <a class="dropdown-item" href="#">Model Selection</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Predict</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{{ url_for('flowchart.flowchart')}}">Data Pipeline</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">User Management</a>
      </li>
    </ul>

    <form class="form-inline my-2 my-lg-0">
      {% if session["email"] %}
        <div class="btn text-muted">User: {{ session["username"] }}</div>

        <a href="{{ url_for('users.logout_user') }}" class="btn btn-sm btn-outline-secondary" id="logoutbutton"> Logout </a>

      {% else %}
        <button type="button" class="btn btn-sm btn-outline-secondary" id="loginbutton">Login</button>
        <button type="button" class="btn btn-sm btn-outline-secondary" id="registerbutton">Register</button>
      {% endif %}
    </form>
  </div>
</nav>

<!-- <br>
<div id="header">
    <img id="logo" src="{{ url_for('static', filename='img/logo.jpg') }}" />
</div>
<br> -->

<div class="content container">
  {% block content %}
  {% endblock %}
</div>


<!-- DROPZONE -->

{{ dropzone.load_js() }}
{{ dropzone.config() }}
{{ dropzone.config(custom_init='dz = this;document.getElementById("submit").addEventListener("click", function handler(e) {dz.processQueue();});',
                     custom_options='autoProcessQueue: false, addRemoveLinks: true, parallelUploads: 20,') }}
<!-- JAVASCRIPT -->

<script type="text/javascript">

  $(document).ready(function(){

    if ( $( "#loginbutton" ).length ) {
      $('#loginbutton').click(function() {
        $( "#basemodalLoginForm" ).modal("show");
      });
    }

    if ( $( "#registerbutton" ).length ) {
      $('#registerbutton').click(function() {
        $( "#basemodalRegisterForm" ).modal("show");
      });
    }

    if ( $( "#usererrorflash" ).length ) {
      $( "#basemodalLoginForm" ).modal("show");

      $('#basemodalLoginForm').on('hidden.bs.modal', function () {
        $( "#usererrorflash" ).remove();
      });
    }

    if ( $( "#usererrorflashregister" ).length ) {
      $( "#basemodalRegisterForm" ).modal("show");

      $('#basemodalRegisterForm').on('hidden.bs.modal', function () {
        $( "#usererrorflashregister" ).remove();
      });
    }

    $("#toggledataupload").click(function() {
        $( "#dataUploadModal" ).modal("show");
        $( "#loadinggif" ).hide();
        $( "#submit").show();
        $( "#modalclosebutton").attr("disabled", false);
        $( "#dataUploadTextArea").prop('readonly', false);
    });

    $("#submit").click(function() {
        $( "#loadinggif" ).show();
        $( "#submit" ).hide();
        $( "#modalclosebutton").attr("disabled", true);
        $( "#dataUploadTextArea").prop('readonly', true);
    });
    
    $('#dataUploadModal').on('hidden.bs.modal', function () {
        $( "#loadinggif" ).hide();
        $( "#submit" ).show();
        $( "#modalclosebutton").attr("disabled", false);
        $( "#dataUploadTextArea").prop('readonly', false);
    });

});
</script>

<!-- Footer -->
<footer class="page-footer font-small blue">
  <!-- Copyright -->
  <div class="footer-copyright text-center py-3"></div>
</footer>

</body>
</html>

src/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Bokeh includes-->
    <link rel="stylesheet" href="http://cdn.pydata.org/bokeh/release/bokeh-1.3.4.min.css" type="text/css" />
    <script type="text/javascript" src="http://cdn.pydata.org/bokeh/release/bokeh-1.3.4.min.js"></script>
  </head>
  <body>
    <div>
        <h1>Bokeh sample</h1>
          {% for plot in plots %}
              {% for part in plot %}
                  {{part | safe}}
              {% endfor %}
          {% endfor %}
    </div>
  </body>
</html>

src/templates/home.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron">
  <h1 class="display-4">Welcome!</h1>
  <p class="lead">Please register for the full expierence.</p>
  <hr class="my-4">
  <p>Here goes more text</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
  </p>
</div>

{% endblock %}

src/templates/html_dependencies.html
<!-- Bootstrap -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
<script src="http://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="http://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>



<!-- Bokeh -->
<link href="http://cdn.pydata.org/bokeh/release/bokeh-1.3.4.min.css" rel="stylesheet" type="text/css">
<link href="http://cdn.pydata.org/bokeh/release/bokeh-widgets-1.3.4.min.css" rel="stylesheet" type="text/css">
<link href="http://cdn.pydata.org/bokeh/release/bokeh-tables-1.3.4.min.css" rel="stylesheet" type="text/css">

<script src="https://cdn.pydata.org/bokeh/release/bokeh-1.3.4.min.js"></script>
<script src="https://cdn.pydata.org/bokeh/release/bokeh-widgets-1.3.4.min.js"></script>
<script src="https://cdn.pydata.org/bokeh/release/bokeh-tables-1.3.4.min.js"></script>
<script src="https://cdn.pydata.org/bokeh/release/bokeh-api-1.3.4.min.js"></script>


<!-- Custom -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" type="text/css"/>

src/templates/macros.html
{% macro render_modal(id, image, item_name, description, screenshot) -%}
<div class="modal fade" id="{{ id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="itemLabel">Modal title</h5>
                {{ image }}
                {{ item_name }}
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="modal-body">
                {{ screenshot }}
            </div>
            <div class="modal-footer">
                {{ description }}
            </div>
        </div>
    </div>
</div> 
{%- endmacro %}



{% macro render_modal_test(id, item_name, description) -%}
<div class="modal fade" id="{{ id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="itemLabel">Modal title</h5>
                {{ item_name }}
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="modal-body">
                {{ description }}
            </div>
            <div class="modal-footer">
                {{ description }}
            </div>
        </div>
    </div>
</div> 
{%- endmacro %}

src/templates/wishlist.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
  <title>Zero To Mastery</title>
</head>

<body>

  <div class="container">
    <div class="row justify-center">
      <div class="col-12">
        <header>
          <h1>Shopping List</h1>

        </header>
        <div class="input-group mb-3">
          <input id="userinput" type="text" class="form-control" placeholder="add an item..." aria-label="Add an item" aria-describedby="basic-addon2">
          <div class="input-group-append">
            <button class="btn btn-outline-info" id="enter" type="button">Add</button>
          </div>
        </div>

      </div>
      <div class="col-12">
        <ul class="list-group">
          <li class="list-group-item">Jello</li>
          <li class="list-group-item">Spinach</li>
          <li class="list-group-item">Rice</li>
          <li class="list-group-item">Birthday Cake</li>
          <li class="list-group-item">Candles</li>
        </ul>
      </div>
    </div>
  </div>





  <!-- Scripts -->
  <script src="../static/js/script.js"></script>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    
  
</body>
<script src="https://code.jquery.com/jquery-3.1.0.js"></script>



</html>