src/models/data/views.py
from flask import Blueprint, request, session, redirect, url_for, render_template
import os
import datetime
import pandas as pd
from src.common.flask_redirect import redirect_url
from src.models.users.decorators import requires_login
from src.models.users.user import User
from src.models.data.data_item import DataItem
from src.common.utils import Utils

data_blueprint = Blueprint('data', __name__)

uploaddir = os.path.join(os.path.dirname(os.path.abspath(__file__)), 
            os.path.normpath('../../../../uploaded'))

logger = Utils.get_logger(__name__)

@data_blueprint.route('/upload', methods=['POST'])
@requires_login
def handle_upload():

    ### Get file descriptions from form ###
    description = "NA" #request.form.get('dataUploadTextArea')


    ### Get user id ###
    userid = User.find_by_email(session["email"])._id

    ### Create data folder ###
    datadir = os.path.join(uploaddir,os.path.normpath("{}/".format(userid)))

    if not os.path.exists(datadir):
        os.mkdir(datadir)

    ### upload data ###
    h5_output_file = os.path.join(datadir,os.path.normpath("userdata.h5"))

    ### Store compress data has hd5
    with pd.HDFStore(h5_output_file, mode='a', complevel=9) as store:

        for key, f in request.files.items():
            if key.startswith('file'):
                
                ### data to server ###
                file = os.path.join(datadir, f.filename)
                f.save(file)

                ### Store csvfile in h5 format ###
                df = DataItem.import_csv(file)
                dataname = DataItem.get_dataset_name(file)
                columnsstring = ','.join(list(df.columns))
                filesize = os.path.getsize(file)

                ctr,dataname0 = 0,dataname
                while '/'+dataname in store.keys():
                    logger.warning("Dataset exists! Changing name in DB.")
                    dataname=dataname0+"_"+str(ctr)
                    ctr+=1

                store.put(dataname, df)                

                ### Create data object ###
                dataItem = DataItem(dataname, h5_output_file, userid, columnsstring, filesize, description=description).save_to_db()

                ### Delete csv file ###
                try:
                    os.remove(file)
                except:
                    logger.warning("Couldn't delete file: {}".format(file))

    return '', 204


@data_blueprint.route('/form', methods=['POST'])
def handle_form():
    description = request.form.get('dataUploadTextArea')
    return 'file uploaded and form submit<br>title: %s<br> description: %s' % ("title", description)


@data_blueprint.route('/explorer')
@requires_login
def explorer():
    return render_template("data/databrowser.html", dataItems=DataItem.getDataItems())
    

@data_blueprint.route('/remove')
@requires_login
def remove():

    
    item = DataItem.find_by_id(request.args.get('dataid'))
    
    if not item is None: 
        item.h5filepath
        item.dataname

        with pd.HDFStore(item.h5filepath) as store:
            store.remove(item.dataname)

        item.remove_from_DB()
        del item;
        return "DataItem deleted successfully!"


    return "Couldn't delete DataItem"

src/templates/data/databrowser.html
{% extends "base.html" %}
{% block content %}

<div class="card-columns">
{% for dataItem in dataItems %}
  <div class="card" id="datacard-{{loop.index}}" name="{{ dataItem._id }}" >
    <div class="card-header">
      <span class="badge badge-secondary">{{ dataItem._id }}</span> Data Item 
    </div>
    <div class="card-body">
      <h5 class="card-title">{{ dataItem.dataname }}</h5>
      <p class="card-text">{{ dataItem.description }}</p>
      <button type="button" class="btn btn-secondary edit" id="itemEditButton-{{loop.index}}">Edit</button>
      <button type="button" class="btn btn-danger delete" id="itemDeleteButton-{{loop.index}}">Delete</button>
      <p class="card-text"><small class="text-muted">Created {{ dataItem.created }}</small></p>
    </div>
  </div>            
{% endfor %}
</div>



<script type="text/javascript">

  $(document).ready(function(){

    //console.log(Object.getOwnPropertyNames($('itemEditButton-1')));

    $('button.btn.btn-secondary.edit').click(function() { 
         var card = $('#'+this.id).parents()[1];
         var dataItemId = $('#'+card.id).attr('name');
         
    });

    $('button.btn.btn-danger.delete').click(function() { 
         var card = $('#'+this.id).parents()[1];
         var dataItemId = $('#'+card.id).attr('name');

          $.ajax({
              url: "{{ url_for('data.remove') }}",
              data: {dataid: dataItemId},
              success: function(data) {
                alert(data);
              }
          });

         $('#'+card.id).remove();
    });


});
</script>


{% endblock %}